# Generated by Django 4.1.1 on 2022-10-15 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="columnas",
            name="tipo_us",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="columnas",
                to="proyectos.tipouserstory",
            ),
        ),
        migrations.AlterField(
            model_name="tipouserstory",
            name="proyeto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proyetos",
                to="proyectos.proyecto",
            ),
        ),
        migrations.AlterField(
            model_name="userstory",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_stories",
                to="proyectos.tipouserstory",
            ),
        ),
    ]
