# Generated by Django 4.1.1 on 2022-10-16 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0004_alter_userstory_fechainicio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tipouserstory",
            name="proyeto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proyectos",
                to="proyectos.proyecto",
            ),
        ),
    ]
