# Generated by Django 4.1.1 on 2022-10-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0007_alter_userstory_estado"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userstory",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="userstory",
            name="identificador",
        ),
    ]
