# Generated by Django 4.1.1 on 2022-10-16 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='desarrollador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.sprint'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stories', to='proyectos.tipouserstory'),
        ),
        migrations.AddField(
            model_name='tipouserstory',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='rol',
            name='grupo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AddField(
            model_name='rol',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='rol',
            name='sprint',
            field=models.ManyToManyField(blank=True, to='proyectos.sprint'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='equipo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='scrumMaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='idPerfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='idProyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='historial',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='columnas',
            name='tipo_us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columnas', to='proyectos.tipouserstory'),
        ),
        migrations.AddField(
            model_name='backlog',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto'),
        ),
        migrations.AlterUniqueTogether(
            name='userstory',
            unique_together={('identificador', 'sprint')},
        ),
        migrations.AlterUniqueTogether(
            name='rol',
            unique_together={('nombre', 'proyecto')},
        ),
    ]
