# Generated by Django 4.1.1 on 2022-10-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backlog",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("Product_Backlog", "Product_Backlog"),
                    ("Sprint_Backlog", "Sprint_Backlog"),
                ],
                max_length=16,
            ),
        ),
    ]
