# Generated by Django 4.1.1 on 2022-10-31 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0003_alter_backlog_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstory",
            name="estado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="proyectos.columnas",
            ),
        ),
    ]
