# Generated by Django 4.1.1 on 2022-10-16 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "proyectos",
            "0003_alter_columnas_tipo_us_alter_tipouserstory_proyeto_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstory",
            name="fechaInicio",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
