# Generated by Django 4.1.1 on 2022-11-01 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0004_alter_userstory_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstory",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="proyectos.sprint",
            ),
        ),
    ]
