# Generated by Django 4.1.1 on 2022-10-16 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0005_alter_tipouserstory_proyeto"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tipouserstory",
            old_name="proyeto",
            new_name="proyecto",
        ),
    ]
