# Generated by Django 4.1.1 on 2022-11-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0006_alter_userstory_backlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sprint",
            name="duracion",
            field=models.FloatField(default=0),
        ),
    ]
