# Generated by Django 4.1.1 on 2022-10-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0006_rename_proyeto_tipouserstory_proyecto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstory",
            name="estado",
            field=models.CharField(blank=True, default="En_Cola", max_length=7),
        ),
    ]
