# Generated by Django 4.1.1 on 2022-11-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0007_alter_sprint_duracion"),
    ]

    operations = [
        migrations.AddField(
            model_name="sprint",
            name="tiempo_disponible",
            field=models.FloatField(default=0),
        ),
    ]
