# Generated by Django 4.1.1 on 2022-11-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0008_sprint_tiempo_disponible"),
    ]

    operations = [
        migrations.AddField(
            model_name="columnas",
            name="opcional",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
