# Generated by Django 4.1.1 on 2022-10-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0008_alter_userstory_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="backlog",
            name="nombre",
            field=models.CharField(default="default", max_length=20),
            preserve_default=False,
        ),
    ]
