# Generated by Django 4.1.1 on 2022-12-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0009_columnas_opcional"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstory",
            name="horas_estimadas",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, null=True, verbose_name="Horas trabajadas"
            ),
        ),
        migrations.AddField(
            model_name="userstory",
            name="horas_trabajadas",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, null=True, verbose_name="Horas trabajadas"
            ),
        ),
    ]
