# Generated by Django 4.1.1 on 2022-12-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0011_miembro_activo_miembro_capacidad_ini_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="columnas",
            name="orden",
            field=models.IntegerField(default=0),
        ),
    ]
