# Generated by Django 4.1.1 on 2022-12-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0013_alter_miembro_idperfil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstory",
            name="descripcion",
            field=models.TextField(default="", null=True),
        ),
    ]
