# Generated by Django 4.1.1 on 2022-12-16 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0014_alter_userstory_descripcion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rol",
            options={
                "permissions": (
                    ("crear_proyecto", "Permite crear proyectos"),
                    ("modificar_proyecto", "Permite modificar proyectos"),
                    ("eliminar_proyecto", "Permite eliminar proyectos"),
                    ("crear_Sprint", "Permite crear un sprint"),
                    ("modificar_Sprint", "Permite modificar un sprint"),
                    ("cancelar_Sprint", "Permite cancelar un sprint"),
                    ("crear_user_story", "Permite crear un user story"),
                    ("modificar_user_story", "Permite modificar un user story"),
                    ("eliminar_user_story", "Permite eliminar un user story"),
                )
            },
        ),
    ]
