# Generated by Django 4.1.1 on 2022-12-16 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0018_alter_rol_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="miembro",
            name="sprint",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="proyectos.sprint",
            ),
            preserve_default=False,
        ),
    ]
