# Generated by Django 4.1.4 on 2022-12-16 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0019_miembro_sprint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="miembro",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="proyectos.sprint",
            ),
        ),
    ]
